// SPDX-License-Identifier: Apache-2.0
//
// Copyright The Prometheus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build windows

package virtdisk

import (
	"golang.org/x/sys/windows"
)

// GET_VIRTUAL_DISK_INFO_VERSION enumeration
type GET_VIRTUAL_DISK_INFO_VERSION uint32

const (
	GET_VIRTUAL_DISK_INFO_UNSPECIFIED                GET_VIRTUAL_DISK_INFO_VERSION = 0
	GET_VIRTUAL_DISK_INFO_SIZE                       GET_VIRTUAL_DISK_INFO_VERSION = 1
	GET_VIRTUAL_DISK_INFO_IDENTIFIER                 GET_VIRTUAL_DISK_INFO_VERSION = 2
	GET_VIRTUAL_DISK_INFO_PARENT_LOCATION            GET_VIRTUAL_DISK_INFO_VERSION = 3
	GET_VIRTUAL_DISK_INFO_PARENT_IDENTIFIER          GET_VIRTUAL_DISK_INFO_VERSION = 4
	GET_VIRTUAL_DISK_INFO_PARENT_TIMESTAMP           GET_VIRTUAL_DISK_INFO_VERSION = 5
	GET_VIRTUAL_DISK_INFO_VIRTUAL_STORAGE_TYPE       GET_VIRTUAL_DISK_INFO_VERSION = 6
	GET_VIRTUAL_DISK_INFO_PROVIDER_SUBTYPE           GET_VIRTUAL_DISK_INFO_VERSION = 7
	GET_VIRTUAL_DISK_INFO_IS_4K_ALIGNED              GET_VIRTUAL_DISK_INFO_VERSION = 8
	GET_VIRTUAL_DISK_INFO_PHYSICAL_DISK              GET_VIRTUAL_DISK_INFO_VERSION = 9
	GET_VIRTUAL_DISK_INFO_VHD_PHYSICAL_SECTOR_SIZE   GET_VIRTUAL_DISK_INFO_VERSION = 10
	GET_VIRTUAL_DISK_INFO_SMALLEST_SAFE_VIRTUAL_SIZE GET_VIRTUAL_DISK_INFO_VERSION = 11
	GET_VIRTUAL_DISK_INFO_FRAGMENTATION              GET_VIRTUAL_DISK_INFO_VERSION = 12
	GET_VIRTUAL_DISK_INFO_IS_LOADED                  GET_VIRTUAL_DISK_INFO_VERSION = 13
	GET_VIRTUAL_DISK_INFO_VIRTUAL_DISK_ID            GET_VIRTUAL_DISK_INFO_VERSION = 14
	GET_VIRTUAL_DISK_INFO_CHANGE_TRACKING_STATE      GET_VIRTUAL_DISK_INFO_VERSION = 15
)

// VIRTUAL_STORAGE_TYPE structure
type VIRTUAL_STORAGE_TYPE struct {
	DeviceID uint32
	VendorID windows.GUID
}

// Size information structure
type GET_VIRTUAL_DISK_INFO_Size struct {
	VirtualSize  uint64
	PhysicalSize uint64
	BlockSize    uint32
	SectorSize   uint32
}

// GET_VIRTUAL_DISK_INFO structure
type GET_VIRTUAL_DISK_INFO struct {
	Version GET_VIRTUAL_DISK_INFO_VERSION
	Size    GET_VIRTUAL_DISK_INFO_Size
}

// OPEN_VIRTUAL_DISK_VERSION enumeration
type OPEN_VIRTUAL_DISK_VERSION uint32

const (
	OPEN_VIRTUAL_DISK_VERSION_UNSPECIFIED OPEN_VIRTUAL_DISK_VERSION = 0
	OPEN_VIRTUAL_DISK_VERSION_1           OPEN_VIRTUAL_DISK_VERSION = 1
	OPEN_VIRTUAL_DISK_VERSION_2           OPEN_VIRTUAL_DISK_VERSION = 2
	OPEN_VIRTUAL_DISK_VERSION_3           OPEN_VIRTUAL_DISK_VERSION = 3
)

// OPEN_VIRTUAL_DISK_FLAG flags
type OPEN_VIRTUAL_DISK_FLAG uint32

const (
	OPEN_VIRTUAL_DISK_FLAG_NONE                           OPEN_VIRTUAL_DISK_FLAG = 0x00000000
	OPEN_VIRTUAL_DISK_FLAG_NO_PARENTS                     OPEN_VIRTUAL_DISK_FLAG = 0x00000001
	OPEN_VIRTUAL_DISK_FLAG_BLANK_FILE                     OPEN_VIRTUAL_DISK_FLAG = 0x00000002
	OPEN_VIRTUAL_DISK_FLAG_BOOT_DRIVE                     OPEN_VIRTUAL_DISK_FLAG = 0x00000004
	OPEN_VIRTUAL_DISK_FLAG_CACHED_IO                      OPEN_VIRTUAL_DISK_FLAG = 0x00000008
	OPEN_VIRTUAL_DISK_FLAG_CUSTOM_DIFF_CHAIN              OPEN_VIRTUAL_DISK_FLAG = 0x00000010
	OPEN_VIRTUAL_DISK_FLAG_PARENT_CACHED_IO               OPEN_VIRTUAL_DISK_FLAG = 0x00000020
	OPEN_VIRTUAL_DISK_FLAG_VHDSET_FILE_ONLY               OPEN_VIRTUAL_DISK_FLAG = 0x00000040
	OPEN_VIRTUAL_DISK_FLAG_IGNORE_RELATIVE_PARENT_LOCATOR OPEN_VIRTUAL_DISK_FLAG = 0x00000080
	OPEN_VIRTUAL_DISK_FLAG_NO_WRITE_HARDENING             OPEN_VIRTUAL_DISK_FLAG = 0x00000100
	OPEN_VIRTUAL_DISK_FLAG_SUPPORT_COMPRESSED_VOLUMES     OPEN_VIRTUAL_DISK_FLAG = 0x00000200
	OPEN_VIRTUAL_DISK_FLAG_SUPPORT_SPARSE_FILES_ANY_FS    OPEN_VIRTUAL_DISK_FLAG = 0x00000400
	OPEN_VIRTUAL_DISK_FLAG_SUPPORT_ENCRYPTED_FILES        OPEN_VIRTUAL_DISK_FLAG = 0x00000800
)

// VIRTUAL_DISK_ACCESS_MASK flags
type VIRTUAL_DISK_ACCESS_MASK uint32

const (
	VIRTUAL_DISK_ACCESS_NONE      VIRTUAL_DISK_ACCESS_MASK = 0x00000000
	VIRTUAL_DISK_ACCESS_ATTACH_RO VIRTUAL_DISK_ACCESS_MASK = 0x00010000
	VIRTUAL_DISK_ACCESS_ATTACH_RW VIRTUAL_DISK_ACCESS_MASK = 0x00020000
	VIRTUAL_DISK_ACCESS_DETACH    VIRTUAL_DISK_ACCESS_MASK = 0x00040000
	VIRTUAL_DISK_ACCESS_GET_INFO  VIRTUAL_DISK_ACCESS_MASK = 0x00080000
	VIRTUAL_DISK_ACCESS_CREATE    VIRTUAL_DISK_ACCESS_MASK = 0x00100000
	VIRTUAL_DISK_ACCESS_METAOPS   VIRTUAL_DISK_ACCESS_MASK = 0x00200000
	VIRTUAL_DISK_ACCESS_READ      VIRTUAL_DISK_ACCESS_MASK = 0x000d0000
	VIRTUAL_DISK_ACCESS_ALL       VIRTUAL_DISK_ACCESS_MASK = 0x003f0000
	VIRTUAL_DISK_ACCESS_WRITABLE  VIRTUAL_DISK_ACCESS_MASK = 0x00320000
)

// OPEN_VIRTUAL_DISK_PARAMETERS structure (Version 1)
type OPEN_VIRTUAL_DISK_PARAMETERS_Version1 struct {
	RWDepth uint32
}

// OPEN_VIRTUAL_DISK_PARAMETERS structure
type OPEN_VIRTUAL_DISK_PARAMETERS struct {
	Version  OPEN_VIRTUAL_DISK_VERSION
	Version1 OPEN_VIRTUAL_DISK_PARAMETERS_Version1
}

// Virtual Storage Type GUIDs
var (
	VIRTUAL_STORAGE_TYPE_DEVICE_UNKNOWN = uint32(0)
	VIRTUAL_STORAGE_TYPE_DEVICE_ISO     = uint32(1)
	VIRTUAL_STORAGE_TYPE_DEVICE_VHD     = uint32(2)
	VIRTUAL_STORAGE_TYPE_DEVICE_VHDX    = uint32(3)
	VIRTUAL_STORAGE_TYPE_DEVICE_VHDSET  = uint32(4)

	VIRTUAL_STORAGE_TYPE_VENDOR_MICROSOFT = windows.GUID{
		Data1: 0xEC984AEC,
		Data2: 0xA0F9,
		Data3: 0x47e9,
		Data4: [8]byte{0x90, 0x1F, 0x71, 0x41, 0x5A, 0x66, 0x34, 0x5B},
	}
)
